version: '2'
services:
  image-injest:
#   use the image from sbt docker:publishLlocal
#    image: image-injest:1.0
#    command: -Dpidfile.path=/dev/null
#   or use the dockerized development environment
    build: .
    command: /usr/src/app/run.sh
    stdin_open: true
#   end
    links:
      - cassandra
    ports:
      - "9000:9000"
      - "9443:9443"
    networks:
      all:
        aliases:
          - image-injest
    environment:
      ENVIRONMENT: local
  cassandra:
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    networks:
      - all
networks:
  all:
    driver: bridge
